name: nfs_alloy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
  
  assets:
    - lib/assets/tyre.json
    - lib/assets/nissinneon.png
    - lib/assets/brushstroke.png